[project]
name = "control"
authors = [
    { name = "Taos Transue", email = "taos.transue@utah.edu" }
]
license = { file = "LICENSE" }
version = "0.1.0"
description = "E(2)-equivariant decentralized controllers"
readme = "README.rst"
requires-python = ">=3.8"
dependencies = [
    "hydra-core>=1.3.2",
    "imageio[ffmpeg]>=2.35.1",
    "ipywidgets>=8.1.5",
    "jupyterlab>=4.3.2",
    "lightning==2.2.1",
    "pytest>=8.3.4",
    "seaborn>=0.13.2",
    "shapely==2.0.2",
    "torch==1.13.1",
    "wandb>=0.18.7",
    # "pyg-lib==0.2.0+pt113cu116",
    # "torch-scatter==2.1.0+pt113cu116",
    # "torch-sparse==0.6.16+pt113cu116",
    # "torch-spline-conv==1.2.1+pt113cu116",
    # "torch-cluster==1.6.0+pt113cu116",
    # "torch-geometric==2.2.0",
]

[project.scripts]
equivariant-decentralized-controllers = "control:main"

[tool.uv]
index-strategy = "unsafe-best-match"
link-mode = "symlink"

[tool.uv.sources]
torch = [
  { index = "pytorch-cu116" },
]
pyg-lib = [
  { index = "pytorch-geometric-cu116" },
]
torch-geometric = [
  { index = "pytorch-geometric-cu116" },
]
torch-scatter = [
  { index = "pytorch-geometric-cu116" },
]
torch-sparse = [
  { index = "pytorch-geometric-cu116" },
]
torch-spline-conv = [
  { index = "pytorch-geometric-cu116" },
]
equivariant-decentralized-controllers = { workspace = true }

[[tool.uv.index]]
name = "pytorch-cu116"
url = "https://download.pytorch.org/whl/cu116"
explicit = true

[[tool.uv.index]]
name = "pytorch-geometric-cu116"
url = "https://data.pyg.org/whl/torch-1.13.0+cu116.html"
explicit = true

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

# [tool.hatch.metadata]
# allow-direct-references = true
#
# [tool.hatch.build.targets.wheel]
# packages = ["src"]
